version: '3.1'

services:

  db:
    build: db
    container_name: test_db
    restart: always
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: users
    ports:
      - 5432:5432
    networks:
      default:
        ipv4_address: 172.16.1.4
  auth:
    container_name: auth_s
    build: auth
    restart: always
    ports:
      - 8081:8081
    networks:
      default:
        ipv4_address: 172.16.1.5
  user:
    container_name: user_s
    build: user
    restart: always
    ports:
      - 8082:8082
    networks:
      default:
        ipv4_address: 172.16.1.2
  proxy:
    container_name: proxy_s
    build: proxy
    restart: always
    ports:
      - 8083:8083
    networks:
      default:
        ipv4_address: 172.16.1.3
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.1.0/24